apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    jsonData:
      httpMethod: POST
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: "postgres"
    isDefault: true
    secureJsonData:
      password: "postgres"
    jsonData:
      database: "electricsim"
      sslmode: "disable"
      postgresVersion: 1700
      timescaledb: false

